version: 0.2
phases:
  install:
    runtime-versions:
      ruby: latest
  build:
    commands:
      - gem install jekyll bundler
      - bundle install
      - echo Starting build
      - bundle exec jekyll build
      - echo Build finished
artifacts:
  name: "BuildOutput"
  files:
    - "**/*"
  exclude-paths:
    - "infrastructure/*"
  base-directory: _site